### ISSUE TITLE
Oauth token, accepted commands and more

### ISSUE THREAD

**Issue by area** [iCart/TwitchPlays#1]
Hey,

I had this idea this morning for a TwitchPlays Fighter, decided to do a quick search, and at it looks like you've maybe had the same idea -- and has started committing some code! I'm mostly interested in having two twitch streams play against each other (there's either a chat for each player, or a prefix for chat commands that maps onto either player one or player two).

Firstly, you seem to have your oAuth token committed to the repository. You... probably don't want that.

Secondly, and this perhaps goes against the 'purity' of the TwitchPlays concept, I think something like a 2d fighter, which relies on combos, will probably be more entertaining to watch if it responds to 'QCF' and 'HCB' commands with the appropriate input. Matches will be much more entertaining with a lot more special moves being thrown around, rather than just random kicks and punches being thrown out.

On the topic of special moves, I am wondering whether something like MvC(2?) would be ideal for this - very showy, lots of exciting animations and special moves that can be button mashed into. I don't know what the state of play regarding emulation is there though.

Anyway, definitely interested in following this and contributing. Just thought I'd throw some ideas out there!

**Comment by iCart** [comment]
Hi,

The goal was also to have two separate streams playing against each other (via Netplay)
Thanks for noticing the oauth token, i'm going to fix that :)

The special moves are something i considered too, i like your idea of adding more special commands.
Probably we could get to a point where we have a generic TwitchPlays repo that would play any game, maybe something that does not depend on a specific emulator (i still have to experiment), and is not platform specific.

Feel free to fork, and submit pull requests, these are always welcome.
