### ISSUE TITLE
Error in the irc.py

### ISSUE THREAD

**Issue by Vrubi** [iCart/TwitchPlays#2]
Hello! I've tried using your work but I ran into some errors that I can not fix. Could you take a look at it, please? :)
![error](https://cloud.githubusercontent.com/assets/24863569/21954419/59dbc696-da50-11e6-9420-2d143eca6319.JPG)

**Comment by iCart** [comment]
Hi,

Your account name should be set in the twitch.conf file. you're not supposed to put it in the code.
Reset that change and update the twitch.conf file, then it should work :-)

**Comment by Vrubi** [comment]
ohh... :D 
Thanks, working now! ;)

**Comment by iCart** [comment]
Glad  i could help!
